### ISSUE TITLE
Exercise 3 - Recommended tcpdump version is patched 

### ISSUE THREAD

**Issue by epi052** [antonio-morales/Fuzzing101#7]
As far as I can tell, tcpdump at tag 4.9.2 contains the patch that fixes the target CVE. 

```
wget https://github.com/the-tcpdump-group/tcpdump/archive/refs/tags/tcpdump-4.9.2.tar.gz\n
tar xf tcpdump-4.9.2.tar.gz
grep -n 'ND_TCHECK\(bp->bp_flags\)' tcpdump-tcpdump-4.9.2/print-bootp.c
325:    ND_TCHECK(bp->bp_flags);
```

ref: https://github.com/the-tcpdump-group/tcpdump/commit/29e5470e6ab84badbc31f4532bb7554a796d9d52

**Comment by Mundi-Xu** [comment]
![image](https://user-images.githubusercontent.com/43680784/143370690-43b0871b-c539-4b4d-96e8-bbca77325b97.png)

Confirm that it has been repaired.
Use the [file](https://github.com/the-tcpdump-group/tcpdump/raw/66e22961b30547e9a8daa1f0e8dc9fbe6e2698fa/tests/bootp_asan-2.pcap)

**Comment by Mundi-Xu** [comment]
![image](https://user-images.githubusercontent.com/43680784/143373471-f351920c-6da3-4bbc-96c1-6900f1d8a3ed.png)

After repeated operations, my libpcap version is different from ![Images/Image1.png](https://github.com/antonio-morales/Fuzzing101/raw/main/Exercise%203/Images/Image1.png), not sure if it is related to this.

**Comment by antonio-morales** [comment]
@epi052 that's true. The commit that fixes the bug is the [following](https://github.com/the-tcpdump-group/tcpdump/commit/85078eeaf4bf8fcdc14a4e79b516f92b6ab520fc#diff-05f854a9033643de07f0d0059bc5b98f3b314eeb1e2499ea1057e925e6501ae8L381)

Thanks for the information 👍 

As thanks, you have been added to the "Thanks" section.

**Comment by mtsio** [comment]
The README stills mentions tcpdump 4.9.2 that contains the patch for the oob read.

**Comment by khokho** [comment]
The version is still incorrect in the readme ...

**Comment by Shenwenkun** [comment]
The version is still incorrect
